### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ElijahRus250** [BRForgers/DisFabric#10]
```---- Minecraft Crash Report ----
// There are four lights!

Time: 1/17/21 12:08 AM
Description: Exception in server tick loop

java.util.concurrent.RejectedExecutionException: The Requester has been stopped! No new requests can be requested!
	at net.dv8tion.jda.internal.requests.Requester.request(Requester.java:106)
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:189)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:411)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:377)
	at br.com.brforgers.mods.disfabric.listeners.MinecraftEventListener.lambda$init$4(MinecraftEventListener.java:79)
	at net.minecraft.class_3324.handler$zha000$remove(class_3324.java:1962)
	at net.minecraft.class_3324.method_14611(class_3324.java)
	at net.minecraft.class_3244.method_10839(class_3244.java:1116)
	at net.minecraft.class_2535.method_10768(class_2535.java:396)
	at net.minecraft.class_3242.method_14357(class_3242.java:186)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 4.19.0-10-amd64
	Java Version: 1.8.0_275, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4806556808 bytes (4583 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 2
	JVM Flags: 20 total; -Xms6144M -Xmx6144M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		blocklogger: Blocklogger 0.3.0
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.2
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		com_mashape_unirest_unirest-java: unirest-java 1.4.9
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.10
		com_squareup_okhttp3_okhttp: okhttp 3.13.0
		com_squareup_okio_okio: okio 1.17.2
		commandaliases: Command Aliases 0.3.0
		commons-codec_commons-codec: commons-codec 1.9
		commons-logging_commons-logging: commons-logging 1.2
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		disfabric: DisFabric 1.2.3
		fabric: Fabric API 0.29.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-mumblelink-mod: MumbleLink 0.7.5
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.11.0
		fastfurnace: FastFurnace 2.3
		jankson: Jankson 3.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 8
		leukocyte: Leukocyte 0.1.2
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		minecraft: Minecraft 1.16.4
		net_dv8tion_jda: JDA 4.2.0_182
		net_sf_trove4j_trove4j: trove4j 3.0.3
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_apache_commons_commons-compress: commons-compress 1.19
		org_apache_httpcomponents_httpasyncclient: httpasyncclient 4.1.1
		org_apache_httpcomponents_httpclient: httpclient 4.5.1
		org_apache_httpcomponents_httpcore: httpcore 4.4.4
		org_apache_httpcomponents_httpcore-nio: httpcore-nio 4.4.4
		org_apache_httpcomponents_httpmime: httpmime 4.5.2
		org_apache_logging_log4j_log4j-slf4j-impl: log4j-slf4j-impl 2.8.1
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		org_json_json: json 20160212
		org_slf4j_slf4j-api: slf4j-api 1.7.25
		org_tukaani_xz: xz 1.8
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.32.3.2
		phosphor: Phosphor 0.7.0+build.10
		player-roles: Player Roles 1.1.2
		serversimplified: Server Simplified 1.1.3
		smoothboot: Smooth Boot 1.16-1.3.1
		spark: spark 1.4.3
		textile_backup: Textile Backup 2.0.1-1.16.3
	Player Count: 3 / 25; [class_3222['SuperSam98'/514278, l='ServerLevel[world]', x=-173.95, y=179.00, z=-185.53], class_3222['HBBrad'/616663, l='ServerLevel[world]', x=-73.70, y=79.75, z=-808.36], class_3222['villk'/617770, l='ServerLevel[world]', x=424.44, y=75.00, z=975.79]]
	Data Packs: vanilla (incompatible), file/VanillaTweaks_c480216.zip, file/VanillaTweaks_c728506.zip, file/afk display v1, file/anti enderman grief v1.0.0 (incompatible), file/double shulker shells v1.2.0 (incompatible), file/more mob heads v2.6.2 (incompatible), file/player head drops v1.0.0 (incompatible), file/villager death messages v1.1.0 (incompatible), file/dragon drops v1 (incompatible), Fabric Mods, file/multiplayer sleep v2.5.2.zip, file/Multiplayer sleep
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)```

**Comment by ElijahRus250** [comment]
I assume this will not have a fix??
