### ISSUE TITLE
Doesn't create config file

### ISSUE THREAD

**Issue by Cazcez** [BRForgers/DisFabric#15]
Hi, i installed the mod to my private server a few minutes ago but when i start the server i only got error at the below and its not creating a config file for setting my bot's token

`[23:43:39] [main/ERROR]: Unable to login!
javax.security.auth.login.LoginException: The provided token is invalid!
	at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:365) ~[68fc6b12-d051-478f-9633-2fddd46f471f.jar:?]
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:282) ~[68fc6b12-d051-478f-9633-2fddd46f471f.jar:?]
	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:249) ~[68fc6b12-d051-478f-9633-2fddd46f471f.jar:?]
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1869) ~[68fc6b12-d051-478f-9633-2fddd46f471f.jar:?]
	at br.com.brforgers.mods.disfabric.DisFabric.onInitializeServer(DisFabric.java:47) ~[disfabric-1.16.4-1.2.3.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) [server.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [server.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) [server.jar:?]
	at net.minecraft.server.Main.main(Main.java:92) [intermediary-vanilla.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [server.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [server.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [server.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [server.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [server.jar:?]
`

**Comment by Cazcez** [comment]
Not creating config folder too

**Comment by allanf181** [comment]
probably an error in fabric or lack of permission on the folder

**Comment by Cazcez** [comment]
Are you sure? other mods are creating folders and files succesfully

**Comment by Cazcez** [comment]
Oh sorry, i feel like a dumb. I'm newbie at fabric and i thought it should create a folder at /mods/ not at /config/
Sorry for false alarm and thanks for your kindness
