### ISSUE TITLE
[Bug] DisFabric won't load: method not found/knot error?

### ISSUE THREAD

**Issue by aksulightning** [BRForgers/DisFabric#30]
Hello, the server won't load DisFabric. I downloaded latest versions of Fabric and Fabric API. Also I post a log, about issue.

Operating system: Debian 10
Java: AdoptOpenJDK-16.0.1+9 (build 16.0.1+9) (64-bit)
Log:
[11:59:42] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'disfabric'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:34) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory: method 'void <init>()' not found
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:53) ~[e4e26127-e96a-4a21-9f92-ebf193a6530b.jar:?]
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:41) ~[e4e26127-e96a-4a21-9f92-ebf193a6530b.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at net.dv8tion.jda.internal.utils.JDALogger.<clinit>(JDALogger.java:49) ~[28d729b5-8237-440a-a993-3ab359299454.jar:?]
        at net.dv8tion.jda.api.utils.SessionControllerAdapter.<clinit>(SessionControllerAdapter.java:41) ~[28d729b5-8237-440a-a993-3ab359299454.jar:?]
        at net.dv8tion.jda.internal.utils.config.SessionConfig.<init>(SessionConfig.java:45) ~[28d729b5-8237-440a-a993-3ab359299454.jar:?]
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1906) ~[28d729b5-8237-440a-a993-3ab359299454.jar:?]
        at br.com.brforgers.mods.disfabric.DisFabric.onInitializeServer(DisFabric.java:53) ~[disfabric-1.17-1.3.2.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more

**Comment by allanf181** [comment]
Full log?

**Comment by aksulightning** [comment]
Full log:
[13:29:26] [main/INFO]: Loading for game Minecraft 1.17
[13:29:28] [main/INFO]: [FabricLoader] Loading 92 mods:
	- adventure-platform-fabric@4.0.0+1.17-SNAPSHOT
	- autoconfig1u@3.3.1
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.34
	- com_fasterxml_jackson_core_jackson-annotations@2.10.1
	- com_fasterxml_jackson_core_jackson-core@2.10.1
	- com_fasterxml_jackson_core_jackson-databind@2.10.1
	- com_google_code_findbugs_jsr305@3.0.2
	- com_konghq_unirest-java_standalone@3.11.9
	- com_neovisionaries_nv-websocket-client@2.14
	- com_squareup_okhttp3_okhttp@3.13.0
	- com_squareup_okio_okio@1.17.2
	- disfabric@1.3.3
	- fabric@0.35.1+1.17
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-api-lookup-api-v1@1.1.0+1d383bb63d
	- fabric-biome-api-v1@3.1.11+c345aea83d
	- fabric-blockrenderlayer-v1@1.1.5+a02b44633d
	- fabric-command-api-v1@1.1.1+a02b44633d
	- fabric-commands-v0@0.2.2+92519afa3d
	- fabric-containers-v0@0.1.12+a02b44633d
	- fabric-content-registries-v0@0.2.2+a02b44633d
	- fabric-crash-report-info-v1@0.1.5+be9da3103d
	- fabric-dimensions-v1@2.0.10+a02b44633d
	- fabric-entity-events-v1@1.1.0+a02b44633d
	- fabric-events-interaction-v0@0.4.8+a02b44633d
	- fabric-events-lifecycle-v0@0.2.1+92519afa3d
	- fabric-game-rule-api-v1@1.0.6+a02b44633d
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab61213d
	- fabric-key-binding-api-v1@1.0.4+a02b44633d
	- fabric-keybindings-v0@0.2.2+36b77c3e3d
	- fabric-language-kotlin@1.6.1+kotlin.1.5.10
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b44633d
	- fabric-mining-levels-v0@0.1.3+92519afa3d
	- fabric-models-v0@0.3.0+a02b44633d
	- fabric-networking-api-v1@1.0.11+b7ab61213d
	- fabric-networking-blockentity-v0@0.2.11+a02b44633d
	- fabric-networking-v0@0.3.2+92519afa3d
	- fabric-object-builder-api-v1@1.10.9+b7ab61213d
	- fabric-object-builders-v0@0.7.3+a02b44633d
	- fabric-particles-v1@0.2.4+a02b44633d
	- fabric-registry-sync-v0@0.7.10+e2961fee3d
	- fabric-renderer-api-v1@0.4.3+676f40fa3d
	- fabric-renderer-indigo@0.4.8+a02b44633d
	- fabric-renderer-registries-v1@3.2.0+a02b44633d
	- fabric-rendering-data-attachment-v1@0.1.5+a02b44633d
	- fabric-rendering-fluids-v1@0.1.13+a02b44633d
	- fabric-rendering-v0@1.1.2+92519afa3d
	- fabric-rendering-v1@1.6.0+a02b44633d
	- fabric-resource-loader-v0@0.4.7+b7ab61213d
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+a02b44633d
	- fabric-structure-api-v1@1.1.10+be9da3103d
	- fabric-tag-extensions-v0@1.1.4+a02b44633d
	- fabric-textures-v0@1.0.6+a02b44633d
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabricloader@0.11.6
	- flan@1.17-1.4.2
	- java@16
	- lithium@0.7.0
	- minecraft@1.17
	- minimotd-fabric@2.0.2
	- net_dv8tion_jda@4.2.1_253
	- net_kyori_adventure-api@4.7.0
	- net_kyori_adventure-key@4.7.0
	- net_kyori_adventure-platform-api@4.0.0-SNAPSHOT
	- net_kyori_adventure-text-feature-pagination@4.0.0-SNAPSHOT
	- net_kyori_adventure-text-minimessage@4.1.0-SNAPSHOT
	- net_kyori_adventure-text-serializer-gson@4.7.0
	- net_kyori_adventure-text-serializer-plain@4.7.0
	- net_kyori_examination-api@1.1.0
	- net_kyori_examination-string@1.1.0
	- net_sf_trove4j_trove4j@3.0.3
	- org_apache_commons_commons-collections4@4.1
	- org_apache_logging_log4j_log4j-slf4j-impl@2.8.1
	- org_jetbrains_annotations@16.0.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.10
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1
	- org_slf4j_slf4j-api@1.7.30
	- org_yaml_snakeyaml@1.25
	- placeholder-api@0.3.0
	- player_events@2.1.2
	- player_events_api@2.1.2
	- playerabilitylib@1.3.0-nightly.1.17-rc1
[13:29:28] [main/WARN]: Mod `net_dv8tion_jda` (4.2.1_253) does not respect SemVer - comparison support is limited.
[13:29:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/purpleruby/servers/minecraft/aksuland60/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[13:29:29] [main/INFO]: Compatibility level set to JAVA_16
[13:29:29] [main/INFO]: Loaded configuration file for Lithium: 77 options available, 0 override(s) found
[13:29:29] [main/WARN]: @Mixin target net/minecraft/class_3218$class_5526 is public in fabric-lifecycle-events-v1.mixins.json:ServerWorldEntityLoaderMixin and should be specified in value
[13:29:30] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[13:29:30] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[13:29:44] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zzh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[13:29:45] [main/INFO]: Done initializing MiniMOTD
[13:29:47] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'disfabric'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:34) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory: method 'void <init>()' not found
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:53) ~[a5f0e5d7-9a64-49d2-9709-325492789900.jar:?]
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:41) ~[a5f0e5d7-9a64-49d2-9709-325492789900.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at net.dv8tion.jda.internal.utils.JDALogger.<clinit>(JDALogger.java:49) ~[6ca93cb9-0da3-4327-a0ec-77523818fb51.jar:?]
	at net.dv8tion.jda.api.utils.SessionControllerAdapter.<clinit>(SessionControllerAdapter.java:41) ~[6ca93cb9-0da3-4327-a0ec-77523818fb51.jar:?]
	at net.dv8tion.jda.internal.utils.config.SessionConfig.<init>(SessionConfig.java:45) ~[6ca93cb9-0da3-4327-a0ec-77523818fb51.jar:?]
	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1906) ~[6ca93cb9-0da3-4327-a0ec-77523818fb51.jar:?]
	at br.com.brforgers.mods.disfabric.DisFabric.onInitializeServer(DisFabric.java:53) ~[disfabric-1.17-1.3.3.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
	... 17 more

**Comment by rogi27** [comment]
I have same problem.
It also says `Could not execute entrypoint stage 'server' due to errors, provided by 'disfabric'`

**Comment by allanf181** [comment]
MiniMOTD includes a lib incompatible with DisFabric

**Comment by allanf181** [comment]
[minimotd-fabric-mc1.17-2.0.3-SNAPSHOT+e50953c.zip](https://github.com/BRForgers/DisFabric/files/6703945/minimotd-fabric-mc1.17-2.0.3-SNAPSHOT%2Be50953c.zip)
try this version of MiniMOTD

**Comment by aksulightning** [comment]
It works.

[latest.log](https://github.com/BRForgers/DisFabric/files/6704316/latest.log)

**Comment by allanf181** [comment]
MiniMOTD developer response:
> There is no 1.17 build released, you are attempting to run a build for 21w15a on 1.17 (so this issue is invalid). When I release a 1.17 build, it will obviously contain the changes for 1.17. Feel free to use a snapshot build from my CI until then: https://jenkins.jpenilla.xyz/job/MiniMOTD/lastSuccessfulBuild/

**Comment by aksulightning** [comment]
Ok.
