### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by TwoPointInfinity** [BRForgers/DisFabric#43]
Server launches fine and runs fine without disfabric.

Other installed mods are:
anti-xray-mc1.18-1.1.1
blockmeter-1.6-fabric_1_18
EditSign-1.18-2.2.5
fabric-api-0.43.1+1.18
LuckPerms-Fabric-5.3.86

```
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: java.lang.RuntimeException: Error creating Mixin config disfabric.mixins.json for mod disfabric
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	... 5 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config disfabric.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
	... 8 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 11 more

```

**Comment by allanf181** [comment]
Java version?

**Comment by TwoPointInfinity** [comment]
Milestone 1 build of IBM Semeru Runtime Open Edition for Java 17 with Eclipse OpenJ9 **jdk-17.0.1**+12_**openj9**-0.29.1-m1

**Comment by allanf181** [comment]
Try this https://www.curseforge.com/minecraft/mc-mods/disfabric/files/3546329

**Comment by TwoPointInfinity** [comment]
Looks like that fixed it boss. You're the fastest cowboy in the west. Thank you.
