### ISSUE TITLE
Can't see minecraft messages in Discord channel

### ISSUE THREAD

**Issue by FlorisFireball** [BRForgers/DisFabric#69]
The joining and server starting messages send. The messages from discord are also forwarded to the Minecraft server, but when you talk in Minecraft, it doesn't forward the message to discord because of an error. It does send the message in the in-game chat.
The log is below. Here are some key lines, I suppose:
`[17:47:16] [Server thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: HTTP host may not be null`

Whole error message:
```
[17:47:16] [Server thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: HTTP host may not be null
[17:47:16] [Server thread/INFO]: [STDERR]: 	at unirest.shaded.org.apache.http.util.Args.notNull(Args.java:54)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at unirest.shaded.org.apache.http.nio.protocol.BasicAsyncRequestProducer.<init>(BasicAsyncRequestProducer.java:91)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at kong.unirest.apache.ApacheAsyncClient.request(ApacheAsyncClient.java:79)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at kong.unirest.AsyncClient.request(AsyncClient.java:67)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at kong.unirest.BaseRequest.asJsonAsync(BaseRequest.java:250)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at br.com.brforgers.mods.disfabric.listeners.MinecraftEventListener.lambda$init$0(MinecraftEventListener.java:90)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at br.com.brforgers.mods.disfabric.events.ServerChatCallback.lambda$static$0(ServerChatCallback.java:14)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.handler$zze000$handleMessage(class_3244.java:2538)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_44155(class_3244.java:1444)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_45064(class_3244.java:1302)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:157)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:131)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:116)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[17:47:16] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:47:16] [Server thread/INFO]: [Not Secure] <MysticMia_basically> Oh no it broke
```

**Comment by allanf181** [comment]
is webhook configured?
